Webnhatro_1900123/Models/TinTuc.cs
using System;
using System.Collections.Generic;

namespace Webnhatro_1900123.Models
{
    public partial class TinTuc
    {
        public string Idnews { get; set; } = null!;
        public string? Title { get; set; }
        public string? NoiDung { get; set; }
        public string? Anh { get; set; }
        public DateTime NgayDang { get; set; }
    }
}

Webnhatro_1900123/Areas/Admin/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Webnhatro_1900123.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace Webnhatro_1900123.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TinTucController : Base
    {
        
        private readonly QuanlynhatroContext _context;
        [Obsolete]
        private readonly IHostingEnvironment _host;

        [Obsolete]
        public TinTucController(QuanlynhatroContext context,IHostingEnvironment host)
        {
           _host = host;
            _context = context;
        }

        // GET: TinTuc
        public async Task<IActionResult> Index(string sortOrder, string Search, string filter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["Date"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["Tieude"] = sortOrder == "title" ? "title_desc" : "title";
            ViewData["Search"] = Search;
            if (Search != null)
            {
                pageNumber = 1;
            }
            else
            {
                Search = filter;
            }
            ViewData["CurrentFilter"] = Search;

            var query = from TinTuc in _context.TinTucs
                                      select TinTuc;
            if (!String.IsNullOrEmpty(Search))//nếu có querystring search=
            {
                query = query.Where(s => s.Title.Contains(Search)
                                       || s.NoiDung.Contains(Search));
                //tìm kiếm bằng Title, nội dung
            }
            switch (sortOrder)// mặc định sx theo ngày đăng
            {
                case "date_desc":
                    query = query.OrderByDescending(s => s.NgayDang); break;
                case "title_desc":
                    query = query.OrderByDescending(s => s.Title); break;
                case "title":
                    query = query.OrderBy(s => s.Title); break;
                default:
                    query = query.OrderBy(s => s.NgayDang);break;
            }
            int pageSize = 5;
            return View(await PaginatedList<TinTuc>.CreateAsync(query.AsNoTracking(), pageNumber ?? 1, pageSize));
            //return View(await query.ToListAsync());
        }



        // GET: TinTuc/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.TinTucs == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.TinTucs.FirstOrDefaultAsync(m => m.Idnews == id);
            if (tinTuc == null)
            {
                return NotFound();
            }

            return View(tinTuc);
        }

        // GET: TinTu/Create
        public IActionResult Create()
        {
                return View();
        }

        // POST: TinTu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Create( TinTuc tinTuc,List<IFormFile> files)
        {
            if (tinTuc.Title!=null&&tinTuc.NoiDung!=null&&files!=null) 
            { 
                var tintuclast = _context.TinTucs.OrderByDescending(s => s.NgayDang).Take(1).ToList();//lấy tin tức có số ID lớn nhất
                tinTuc.Idnews = "News" + Convert.ToString(Convert.ToInt32(tintuclast[0].Idnews.Replace("News", "")) + 1);//gán Id tintuc = News+số ID lớn nhất +1
                tinTuc.NgayDang = DateTime.Now;
                    //lưu ảnh vào thư mục 
                    foreach (var file in files)
                    {
                        string filename = file.FileName;
                        string fileextension = Path.GetExtension(filename);
                        filename = tinTuc.Idnews + "_Anh" + fileextension;
                        var pathsave = Path.Combine(_host.WebRootPath + @"\Upload\News", filename);//đường đãn lưu file  _host.WebRootPath:chỉ wwwroot 
                        if (System.IO.File.Exists(pathsave))//nếu đã tồn tại-->xoá-->lưu
                        {
                            System.IO.File.SetAttributes(pathsave, FileAttributes.Normal);
                            System.IO.File.Delete(pathsave);
                            using var stream = new FileStream(pathsave, FileMode.Create);
                            file.CopyTo(stream);
                        }
                        else//chưa có thực hiện lưu vào thư mục
                        {
                            using var stream = new FileStream(pathsave, FileMode.Create);
                            file.CopyTo(stream);

                        }
                        tinTuc.Anh += $"{filename}";

                    }
                    //
                        _context.Add(tinTuc);
                        await _context.SaveChangesAsync();
                        TempData["Thongbao"] = "Đã thêm thành công";
                        return RedirectToAction(nameof(Index));
            }
            else
            TempData["Thongbao"] = "Thất bại, kiểm tra lại dữ liệu nhập";
            return View(tinTuc);
        }

        // GET: TinTu/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.TinTucs == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.TinTucs.FindAsync(id);
            if (tinTuc == null)
            {
                return NotFound();
            }
            return View(tinTuc);
        }

        // POST: TinTu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Edit(string id, [Bind("Idnews,Title,NoiDung")] TinTuc tinTuc, List<IFormFile> files)
        {
            tinTuc.NgayDang = DateTime.Now;
            //lưu ảnh vào thư mục 
            int i = 1;
            if (files.Count != 0)
            {
                foreach (var file in files)
                {
                    string filename = file.FileName;
                    string fileextension = Path.GetExtension(filename);
                    filename = tinTuc.Idnews + "_Anh" + i.ToString() + fileextension;
                    var pathsave = Path.Combine(_host.WebRootPath + @"\Upload\News", filename);//đường đãn lưu file  _host.WebRootPath:chỉ wwwroot 
                    if (System.IO.File.Exists(pathsave))//nếu đã tồn tại-->xoá-->lưu
                    {
                        System.IO.File.SetAttributes(pathsave, FileAttributes.Normal);
                        System.IO.File.Delete(pathsave);
                        using var stream = new FileStream(pathsave, FileMode.Create);
                        file.CopyTo(stream);
                    }
                    else//chưa có thực hiện lưu vào thư mục
                    {
                        using var stream = new FileStream(pathsave, FileMode.Create);
                        file.CopyTo(stream);

                    }
                    tinTuc.Anh = $"{filename}";
                    i++;
                }
            }
            else//nếu không có ảnh upload
            {
                var oldnews= await _context.TinTucs.FindAsync(id);//lấy tintuc dang sửa
                if(oldnews!=null)
                    tinTuc.Anh = oldnews.Anh;//gán tên ảnh bằng tên cũ;
            }
           
            //
            if (id != tinTuc.Idnews)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tinTuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TinTucExists(tinTuc.Idnews))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tinTuc);
        }
        // POST: TinTu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Delete(string id)
        {
            if (_context.TinTucs == null)
            {
                return Problem("Entity set 'QuanlynhatroContext.TinTucs'  is null.");
            }
            var tinTuc = await _context.TinTucs.FindAsync(id);
            if (tinTuc != null)
            {   
                if(tinTuc.Anh != null)
                {
                    var pathsave = Path.Combine(_host.WebRootPath + @"\Upload\News", tinTuc.Anh);
                        System.IO.File.SetAttributes(pathsave, System.IO.FileAttributes.Normal);
                        System.IO.File.Delete(pathsave);
                }
                _context.TinTucs.Remove(tinTuc);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        string format(string data)
        {
            data = data.Replace(';', ';');
            return data;
        }
        private bool TinTucExists(string id)
        {
          return _context.TinTucs.Any(e => e.Idnews == id);
        }
    }
}

Webnhatro_1900123/Areas/Admin/Views/TinTuc/Create.cshtml
@model Webnhatro_1900123.Models.TinTuc

@{
    ViewData["Title"] = "Tạo mới";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}
<link rel="stylesheet" href="~/Template/dist/assets/vendors/quill/quill.snow.css"/> 

<h1>Đăng tin</h1>

@using (Html.BeginForm("Create","TinTuc" ,FormMethod.Post,new {@enctype="multipart/form-data"}))
{
<hr />

<div class="card-content">
	<div class="card-body">
		 <form class="form form-vertical" method="post">
			 <div class="row">
				 <div class="col-12">
						<div class="form-group has-icon-left">
							<label for="first-name-icon">Tiêu đề tin</label>
							<div class="position-relative">
								<input type="text" class="form-control" asp-for="Title" placeholder="Nhập tiêu đề">
								<div class="form-control-icon"><i class="bi-layout-three-columns"></i></div>
							</div>
						</div>
                  </div>
				 
				   <div class="col-12 ">
						<div class="form-group has-icon-left">
							<label for="first-name-icon">Ảnh</label>
							<div class="position-relative">
							<input asp-for="Anh" id="files" name="files" type="file" accept="image/*" />  	
									
							</div>
						</div>
				   </div>
				   <div class="col-12 bg-white">
						<div class="form-group">
							<label for="first-name-icon">Nội dung tin</label>
							<div class="position-relative">
								<input  name="NoiDung" type="hidden" asp-for="NoiDung">
								<div id="editor-container"></div>
							</div>
						</div>
                  </div>
			 </div>
			 <div class="mb-3 mt-2">
				 <input class="btn btn-primary me-1 mb-1 position-absolute" style="margin:auto;display:block" type="submit" value="Create">
			 </div>
			 

		 </form>
	</div>
</div>


<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div>
}
<script src="~/Template/dist/assets/vendors/quill/quill.min.js"></script>
<script src="~/js/app.js"></script>
@section Scripts 
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webnhatro_1900123/Areas/Admin/Views/TinTuc/Details.cshtml
@model Webnhatro_1900123.Models.TinTuc

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}


    <div class="row grid-responsive">
        <div class="column ">
            <div class="card">
                <div class="card-title">
                    <h3>Chi tiết bài viết</h3>
                </div>
                <div class="card-block">
                    <dl>
                        <dt><b>Tiêu đề</b></dt>
                        <dd>@Html.DisplayFor(model => model.Title)</dd>
                        <dt><b>Ảnh</b></dt>
                        <dd>
                            @if (!string.IsNullOrEmpty(Model.Anh))
                            {
                                <img src="~/Upload/News/@Model.Anh"/>
                            }  
                        </dd>
                            <dt><b>Nội dung</b></dt>
                            <dd>@Html.Raw(Model.NoiDung)</dd>
                            <dt><b>Ngày đăng</b></dt>
                            <dd >@Html.DisplayFor(model => model.NgayDang)</dd>
                        </dl>    
						</div>
					</div>
				</div>
			</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Idnews" class="button">Sửa </a> |
    <a asp-action="Index">Về danh sách</a>
</div>

Webnhatro_1900123/Areas/Admin/Views/TinTuc/Edit.cshtml
@model Webnhatro_1900123.Models.TinTuc

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}
<link rel="stylesheet" href="~/Template/dist/assets/vendors/quill/quill.snow.css"/> 

<h1>Edit</h1>
<h4>TinTuc</h4>
<hr />
@using (Html.BeginForm("Edit","TinTuc" ,FormMethod.Post,new {@enctype="multipart/form-data"}))
{
<div class="card-content">
	<div class="card-body">
		 <form class="form form-vertical" asp-action="Edit">
			 <div class="row">
				 <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idnews" />
				 <div class="col-12">
								<div class="form-group has-icon-left">
									<label for="first-name-icon">Tiêu đề tin</label>
									<div class="position-relative">
								<input type="text" class="form-control" asp-for="Title" placeholder="Nhập tiêu đề">
										<div class="form-control-icon">
											<i class="bi-layout-three-columns"></i>
									</div>
									</div>
							</div>
                  </div>
				   <div class="col-12">
								<div class="form-group has-icon-left">
									<label for="first-name-icon">Ảnh</label>
									<div class="position-relative">
								 <input asp-for="Anh" id="files" multiple name="files" type="file" accept="image/*" />  	
									</div>
								</div>
				 </div>
				  <div class="col-12 bg-white">
						<div class="form-group">
							<label for="first-name-icon">Nội dung tin</label>
							<div class="position-relative">
								<input  name="NoiDung" type="hidden" asp-for="NoiDung">
								<div id="editor-container"></div>
							</div>
						</div>
                  </div>
				 
			 </div>
					<input type="submit" value="Save" class="btn btn-primary" />
		 </form>
	</div>
</div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>
<script src="~/Template/dist/assets/vendors/quill/quill.min.js"></script>
<script src="~/js/app.js"></script>
@section Scripts {@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webnhatro_1900123/Areas/Admin/Views/TinTuc/Index.cshtml
@model PaginatedList<Webnhatro_1900123.Models.TinTuc>

@{
    ViewData["Title"] = "Danh sách tin tức";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}

<h1>Quản lý tin tức</h1>

<p>
    <a asp-action="Create">Tạo tin tức mới</a>
</p>

<div class="card px-1">
<div>
<div class="card-body px-0">
	<form method="get">
        <div class="input-group mb-3">
            <span class="input-group-text" ><i class="bi bi-search"></i></span>
                                                   
                <input type="text" class="form-control" placeholder="Nhập tiêu đề hoặc nội dung"  name="Search" value="@ViewBag.search" >
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Tìm kiếm</button>
        </div>
      </form> 
<div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns">
<div class="dataTable-container">
<table class="table table-striped dataTable-table" >
								<thead>
									<tr>
										<th> <a asp-action="Index" asp-route-sortOrder="@ViewData["Tieude"]">Tiêu đề</a> </th>
										<th>Nội dung</th>
										<th>Ảnh</th>
										<th> <a asp-action="Index" asp-route-sortOrder="@ViewData["Date"]">Ngày đăng</a></th>
									</tr>
								</thead>
                                <tbody>
                @foreach(var item in Model)
                {
					<tr>
						<td><a asp-action="Details" asp-route-id="@item.Idnews" >@item.Title </a></td>
						<td><a asp-action="Details" asp-route-id="@item.Idnews" >Click vào để xem nội dung </a></td>
						<td>
                            <a asp-action="Details" asp-route-id="@item.Idnews"> @item.Anh.Split(';').Count() ảnh (xem chi tiết)</a></td>
						<td>@item.NgayDang</td>
                        <td>       
								<a class="btn btn-sm btn-info" style="color:#fff"  asp-action="Edit" asp-route-id="@item.Idnews" > Sửa </a>
									<form method="post">
                                    <button class="btn btn-sm btn-danger" style="color:#fff" asp-action="Delete" type="submit" name="id" value="@item.Idnews">Xoá</button>
                            </form>
                                           
                        </td>
					</tr>
                }
								</tbody>
							</table>
    <div class="dataTable-bottom">
        <div class="dataTable-info">Trang @Model.PageIndex / @Model.TotalPages</div>
	    <ul class="pagination pagination-primary float-end dataTable-pagination">

             @if (Model.HasPreviousPage)
        {
        <li class="page-item pager"><a asp-action="Index"
        asp-route-sortOrder="@ViewData["CurrentSort"]" 
        asp-route-pageNumber="@(Model.PageIndex - 1)"
        asp-route-currentFilter="@ViewData["CurrentFilter"]" class="page-link" >‹ trang trước</a></li>
        }
        @if (Model.HasNextPage)
        {
            <li class="page-item pager"><a  asp-action="Index"
                asp-route-sortOrder="@ViewData["CurrentSort"]"
                asp-route-pageNumber="@(Model.PageIndex + 1)"
                asp-route-currentFilter="@ViewData["CurrentFilter"]"
                class="page-link" >trang sau ›</a></li>
        }
      </ul>

    </div>
    </div>
    </div>
    </div>
</div>
</div>