Webnhatro_1900123/Models/NhaTro.cs
using System;
using System.Collections.Generic;

namespace Webnhatro_1900123.Models
{
    public partial class NhaTro
    {
        public string Idtro { get; set; } = null!;
        public string? TieuDe { get; set; }
        public int? Dientich { get; set; }
        public int Gia { get; set; }
        public string? Thongtin { get; set; }
        public string? Anh { get; set; }
        public DateTime Thoigiandang { get; set; }
        public string? Idxa { get; set; }
        public string? Username { get; set; }

        public virtual Xa? IdxaNavigation { get; set; }
        public virtual Member? UsernameNavigation { get; set; }
    }
}

Webnhatro_1900123/Areas/Admin/Controllers/NhaTroController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Webnhatro_1900123.Models;
using System.Web;
using System.IO;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.Net.Http.Headers;

namespace Webnhatro_1900123.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NhaTroController : Base
    {
       
        private readonly QuanlynhatroContext _context;
        [Obsolete]
        private readonly IHostingEnvironment _host;
        [Obsolete]
        public NhaTroController(QuanlynhatroContext context, IHostingEnvironment host)
        {
            _host = host;
            _context = context;
        }
        String getdiachi(string id)
        {
            string diachi="";
            var query = (
              from NhaTro in _context.NhaTros
              join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
              join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
              join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
              where NhaTro.Idtro == id
              select new
              {
                  Xa = Xa.TenXa,
                  KhuVuc = KhuVuc.TenKhuVuc,
                  Tinh = Tinh.TenTinh
              });
            foreach(var item in query.ToList())
            {
                diachi = $"{item.Xa}-{item.KhuVuc}-{item.Tinh}";
            }
            return diachi;
        }
       List<Tinh> GetTinh()
        {
            var query = from Tinh in _context.Tinhs select Tinh;
            return query.ToList();
        }
        List<KhuVuc> GetKhuVuc(string idtinh)
        {
           // List<KhuVuc> kv = new List<KhuVuc>();
            var Khuvuc = from KhuVuc in _context.KhuVucs
                                where KhuVuc.Idtinh == idtinh
                                select KhuVuc;
            return Khuvuc.ToList();
            
        }
    // GET: NhaTro
    public async Task<IActionResult> Index( string? Search, int? pageNumber,string? price, string? sortOrder)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["UserName"] = sortOrder=="username"? "username_desc" : "username";
            ViewData["Gia"] = sortOrder == "gia" ? "gia_desc" : "gia";
            ViewData["Dientich"] = sortOrder == "dientich" ? "dientich_desc" : "dientich";
            ViewData["Date"] = sortOrder == "date" ? "date_desc" : "date";
            ViewData["Search"] = Search;
            if (Search != null)
            {
                pageNumber = 1;
            }
            ViewData["CurrentFilter"] = Search;

            IQueryable<Nhatrofull> query = (
              from NhaTro in _context.NhaTros
              join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
              join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
              join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
              select new Nhatrofull 
              {
                  ObjNhaTro=NhaTro,
                  ObjXa = Xa,
                  ObjKhuVuc = KhuVuc,
                  ObjTinh = Tinh
              });
            if (!string.IsNullOrEmpty(price))
            {
                switch (price)
                {
                    case "1":
                        query = query.Where(s => s.ObjNhaTro.Gia <= 1000000);
                        break;
                    case "2":
                        query = query.Where(s => s.ObjNhaTro.Gia > 1000000 && s.ObjNhaTro.Gia<=3000000);
                        break;
                    case "3":
                        query = query.Where(s => s.ObjNhaTro.Gia >3000000 && s.ObjNhaTro.Gia<=7000000);
                        break;
                    case "4":
                        query = query.Where(s => s.ObjNhaTro.Gia >7000000);
                        break;
                }
            }
            if (!String.IsNullOrEmpty(Search))//nếu có querystring search=
            {
                query = query.Where(s => s.ObjNhaTro.TieuDe.Contains(Search)
                                       || s.ObjXa.TenXa.Contains(Search)||s.ObjNhaTro.Username.Contains(Search));
                //tìm kiếm bằng tiêu đề, username, giá,diện tích
            }
            switch (sortOrder)
            {
                case "username_desc":
                    query = query.OrderByDescending(s => s.ObjNhaTro.Username);
                    break;
                case "username":
                    query = query.OrderBy(s => s.ObjNhaTro.Username);
                    break;
                case "date":
                    query = query.OrderBy(s => s.ObjNhaTro.Thoigiandang);
                    break;
                case "date_desc":
                    query = query.OrderByDescending(s => s.ObjNhaTro.Thoigiandang);
                    break;
                case "gia":
                    query = query.OrderBy(s => s.ObjNhaTro.Gia);
                    break;
                case "gia_desc":
                    query = query.OrderByDescending(s => s.ObjNhaTro.Gia);
                    break;
                case "dientich":
                    query = query.OrderBy(s => s.ObjNhaTro.Dientich);
                    break;
                case "dientich_desc":
                    query = query.OrderByDescending(s => s.ObjNhaTro.Dientich);
                    break;
                default:
                    query = query.OrderBy(s => s.ObjNhaTro.Idtro);
                    break;
            }
            int pageSize = 5;
            //var quanlynhatroContext = _context.NhaTros.Include(n => n.IdxaNavigation).Include(n => n.UsernameNavigation);
            //ViewData["full"] = full();
            //return View(await quanlynhatroContext.ToListAsync());
              //return View();
              
            return View(await PaginatedList <Nhatrofull>.CreateAsync(query.AsNoTracking(),pageNumber??1,pageSize));
        }

        // GET: NhaTro/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.NhaTros == null)
            {
                return NotFound();
            }
            ViewData["DiaChi"] = getdiachi(id);
            var nhaTro = await _context.NhaTros
                .Include(n => n.IdxaNavigation)
                .Include(n => n.UsernameNavigation)
                .FirstOrDefaultAsync(m => m.Idtro == id);
            if (nhaTro == null)
            {
                return NotFound();
            }

            return View(nhaTro);
        }

        // GET: NhaTro/Create
        public IActionResult Create()
        {
            ViewData["Username"]=new SelectList(_context.Members, "Username","HoTen");
             return View();
        }

        // POST: NhaTro/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Create(NhaTro nhaTro,List<IFormFile> files )
        {
            nhaTro.Thoigiandang = DateTime.Now;
            var Nhatrolast = _context.NhaTros.OrderByDescending(s => s.Idtro).Take(1).ToList();//lấy Phòng trọ có số ID lớn nhất
            nhaTro.Idtro = "TRO" + Convert.ToString(Convert.ToInt32(Nhatrolast[0].Idtro.Replace("TRO", "")) + 1);//gán Id trọ = TRO+số ID lớn nhất +1
            //thêm ảnh vào thư mục upload
            if (files != null&& nhaTro.Idtro != null && nhaTro.Idxa != null &&
               nhaTro.TieuDe != null && nhaTro.Thongtin != null &&
               nhaTro.Gia != 0 && nhaTro.Dientich != 0)
            {
                int i = 1;
                foreach (var file in files)
                {
                    string filename = file.FileName;
                    string fileextension = Path.GetExtension(filename);
                    filename = nhaTro.Idtro + "_Anh" + i.ToString() + fileextension;
                    var pathsave = Path.Combine(_host.WebRootPath + @"\Upload\NhaTro", filename);//đường đãn lưu file  _host.WebRootPath:chỉ wwwroot 
                    if (System.IO.File.Exists(pathsave))//nếu đã tồn tại-->xoá-->lưu
                    {
                        System.IO.File.SetAttributes(pathsave, FileAttributes.Normal);
                        System.IO.File.Delete(pathsave);
                        using var stream = new FileStream(pathsave, FileMode.Create);
                        file.CopyTo(stream);
                    }
                    else//chưa có thực hiện lưu vào thư mục
                    {
                        using var stream = new FileStream(pathsave, FileMode.Create);
                        file.CopyTo(stream);
                        
                    }
                    nhaTro.Anh += $"{filename};";
                    i++;
                }
                    _context.Add(nhaTro);
                   await _context.SaveChangesAsync();
                 ViewBag.Messenger = "success";

                return  RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["Username"] = new SelectList(_context.Members, "Username", "Username");
                TempData["Thongbao"] = "Lỗi! vui lòng kiểm tra lại dữ liệu nhập";
                    return View();
            }
          
        }
    
        // GET: NhaTro/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.NhaTros == null)
            {
                return NotFound();
            }
            ViewData["DiaChi"] = getdiachi(id);
            var nhaTro = await _context.NhaTros.FindAsync(id);
            IQueryable getmember=from Member in _context.Members select Member;
            ViewData["Member"] = getmember;
            if (nhaTro == null)
            {
                return NotFound();
            }
            return View(nhaTro);
        }

        // POST: NhaTro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]

Webnhatro_1900123/Areas/Admin/Views/NhaTro/Create.cshtml
@model Webnhatro_1900123.Models.NhaTro

@{
    ViewData["Title"] = "Tạo mới nhà trọ";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
    
}
<link rel="stylesheet" href="~/Template/dist/assets/vendors/quill/quill.snow.css"/> 

<h1 class="card-title">Tạo mới Nhà Trọ </h1>
@if (TempData["Thongbao"] != null)
{
   <div class="alert alert-danger alert-dismissible show fade"> @TempData["Thongbao"]</div>
}
@using (Html.BeginForm("Create","NhaTro" ,FormMethod.Post,new {@enctype="multipart/form-data"}))
{
  <div class="card-content">
                                    <div class="card-body">
                                        <form class="form form-vertical" method="post">
                                            <div class="form-body">
                                                <div class="row">
                                                    <div class="col-12">
                                                        <div class="form-group has-icon-left">
                                                            <label for="first-name-icon">Nhập tiêu đề</label>
                                                            <div class="position-relative">
                                                                <input type="text" class="form-control" asp-for="TieuDe" placeholder="Nhập tiêu đề" id="first-name-icon">
                                                                <div class="form-control-icon">
                                                                    <i class="bi-layout-three-columns"></i>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-12">

                                                        <div class="form-group has-icon-left">
                                                         <label for="email-id-icon">Địa chỉ</label>
                                                            <div class="position-relative">
                                                                 <select class="btn btn-light dropdown-toggle dropdown-toggle-split show" style="background-color:#fff"    id="city" name="tinh">
                                                                <option   value="" selected>Chọn tỉnh thành</option>           
                                                                </select>
          
                                                                <select class="btn btn-light dropdown-toggle dropdown-toggle-split show" style="background-color:#fff "   id="district" name="khuvuc" >
                                                                <option value="" selected>Chọn quận huyện</option>
                                                                </select>

                                                                 <select class="btn btn-light dropdown-toggle dropdown-toggle-split show" style="background-color:#fff"   asp-for="Idxa" id="ward" name="Idxa">
                                                                <option value="" selected>Chọn phường xã</option>
                                                                </select>     
                                                             </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-12">
                                                        <div class="form-group has-icon-left">
                                                            <label>Diện tích </label>
                                                            <div class="position-relative">
                                                                <input type="text" class="form-control" asp-for="Dientich" placeholder="diện tích m2" >
                                                                <div class="form-control-icon">
                                                                    <i class="bi-rulers"></i>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-12">
                                                        <div class="form-group has-icon-left">
                                                            <label >Giá Cho thuê</label>
                                                            <div class="position-relative">
                                                                <input type="number" class="form-control" asp-for="Gia" placeholder="nhập số tiền..." >
                                                                <div class="form-control-icon">
                                                                    <i class="bi-wallet"></i>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                   
                                                    <div class="col-12">
                                                        <div class="form-group has-icon-left">
                                                            <label>Ảnh</label>
                                                            <div class="position-relative">
                                                                <input  class="form-control" asp-for="Anh" id="files" multiple name="files" type="file" accept="image/*">
                                                                <div class="form-control-icon">
                                                                    <i class="bi-image"></i>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-12">
                                                        <div class="form-group has-icon-left">
                                                            <label>Thành viên đăng :</label>                                                           
                                                                <select class="btn btn-light dropdown-toggle dropdown-toggle-split show" style="background-color:#fff"  asp-for="Username"  asp-items="ViewBag.Username"></select>
                                                        </div>
                                                    </div>
                                                     <div class="col-12 bg-white">
						                                <div class="form-group">
							                                <label for="first-name-icon">Nội dung tin</label>
							                                <div class="position-relative">
                                                                    <input  name="Thongtin" type="hidden" asp-for="Thongtin" >
								                                <div id="editor-container"></div>
							                                </div>
						                                </div>
                                                    </div>
                                                     <div class="mb-3 mt-2">
			                                            <input class="btn btn-primary me-1 mb-1 position-absolute" style="margin:auto;display:block" type="submit" value="Create">
		                                             </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
  </div>


}
<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div>
<script src="~/js/axios.min.js"></script>
<script src="~/js/Diadiem.js"></script>
<script src="~/Template/dist/assets/vendors/quill/quill.min.js"></script>
<script src="~/js/quillhouse.js"></script>
@section Scripts 
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webnhatro_1900123/Areas/Admin/Views/NhaTro/Details.cshtml
@model Webnhatro_1900123.Models.NhaTro

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}
<h4>Thông tin Nhà Trọ</h4>
<div class="row grid-responsive">
    <div class="column ">
					<div class="card">
                        <hr />
                       <dl>
                           <dt><b>Ảnh</b></dt>
                           <dd>
                               @if(Model.Anh!=null)
                               @foreach (var anh in Model.Anh.Split(';'))
                               { 
                                   if (anh.Length != 0)
                                   {
                                     <img style="width:132px;height132px" src="~/Upload/NhaTro/@anh"/>
                                   }
                        
                                }  
                           </dd>
                           <dt><b>Tiêu đề</b></dt><dd>@Model.TieuDe</dd>
                           <dt><b>Địa chỉ</b></dt><dd>@ViewData["DiaChi"]</dd>
                           <dt><b>Diện tích</b></dt><dd>@Model.Dientich</dd>
                           <dt><b>Giá</b></dt><dd>@Model.Gia.ToString("#,###") VNĐ</dd>
                           <dt><b>Thông tin</b></dt><dd>@Html.Raw(Model.Thongtin)</dd>
                           <dt><b>Thời gian đăng</b></dt><dd>@Model.Thoigiandang</dd>
                           <dt><b>Người đăng</b></dt><dd>@Model.Username</dd>
       
                       </dl>    
                     </div>
    </div>
 </div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Idtro" class="button">Sửa</a> |
    <a asp-action="Index">Về danh sách</a>
</div>
<script>
    var myCarousel = document.querySelector('#myCarousel')
var carousel = new bootstrap.Carousel(myCarousel)
</script>

Webnhatro_1900123/Areas/Admin/Views/NhaTro/Edit.cshtml
@model Webnhatro_1900123.Models.NhaTro

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}
<link rel="stylesheet" href="~/Template/dist/assets/vendors/quill/quill.snow.css"/> 

<h1 class="card-title">Thông tin nhà trọ</h1>
<hr />
@if (TempData["Thongbao"] != null)
{
    <div class="alert alert-warning fs-2"><i class="bi bi-exclamation-triangle"></i> 
        @TempData["Thongbao"];
    </div>
}
@using (Html.BeginForm("Edit","NhaTro" ,FormMethod.Post,new {@enctype="multipart/form-data"}))
{
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idtro" />
            <div class="form-group">
                <label asp-for="TieuDe" class="control-label"></label>
                <input asp-for="TieuDe" class="form-control" />
                <span asp-validation-for="TieuDe" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label  class="control-label">Địa Chỉ</label>
               <div>
                    <select class="form-select form-select-sm mb-3"  id="city" aria-label=".form-select-sm">
                    <option value="" selected>Chọn tỉnh thành</option>           
                    </select>
          
                    <select class="form-select form-select-sm mb-3" id="district" aria-label=".form-select-sm">
                    <option value="" selected>Chọn quận huyện</option>
                    </select>

                    <select class="form-select form-select-sm" asp-for="Idxa" id="ward" aria-label=".form-select-sm">
                    <option value="@Model.Idxa" selected="selected"  >Chọn phường xã</option>
                    </select>
                </div>    
             
            </div>
            <div class="form-group">
                <label asp-for="Dientich" class="control-label">Diện tích</label>
                <input asp-for="Dientich" class="form-control" />
                <span asp-validation-for="Dientich" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group bg-white">
                <label asp-for="Thongtin" class="control-label bg-light">Thông tin</label>
                 <span asp-validation-for="Thongtin" class="text-danger"></span>
                 <input  name="Thongtin" type="hidden" asp-for="Thongtin" >
				<div id="editor-container"></div>
            </div>
            <div class="form-group" >
                
                    <div class="col-md-10">
                        <label class="=control-label"> Ảnh (Upload lại sẽ xoá ảnh cũ)</label>
                        <input asp-for="Anh" id="files" name="files" type="file" multiple accept="image/*" />                
                    </div>
                </div>
            <div class="form-group">
                <label class="control-label">Người đăng</label>
                <select asp-for="Username" >
                   <option selected >@Model.Username</option>
                    </select>
                
            </div>
            <div class="form-group" >
                <button type="submit" asp-action="Edit" class="button">Lưu</button>
            </div>
        </form>
    </div>
</div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}


<script src="~/js/axios.min.js"></script>
<script src="~/js/Diadiem.js"></script>
<script src="~/Template/dist/assets/vendors/quill/quill.min.js"></script>
<script src="~/js/quillhouse.js"></script>

Webnhatro_1900123/Areas/Admin/Views/NhaTro/Index.cshtml
@model PaginatedList<Webnhatro_1900123.Models.Nhatrofull>
@{
    ViewData["Title"] = "phòng trọ đã đăng";
    Layout = "~/Views/Shared/_Layoutadmin.cshtml";
}

<h1 class="card-title">Danh sách nhà trọ</h1>

<p>
    <a  asp-action="Create">Tạo mới</a>
</p>
<div class="card">
<div class="card-header p-0">
<div class="card-body p-0">
    	<form method="get">
            <div class="btn-group dropdown me-1 mb-1">
                <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-reference="parent">
                    <span class="sr-only">Lọc theo mức giá</span>
                </button>
                <div class="dropdown-menu" style="margin: 0px;">
                    <button type="submit" class="dropdown-item" asp-action="Index"  name="price" value="1" >Dưới 1 triệu</button>
                    <button  type="submit"  class="dropdown-item" asp-action="Index" name="price" value="2">Từ 1 đến 3 triệu</button>
                    <button type="submit"  class="dropdown-item" asp-action="Index" name="price" value="3" >Từ 3 đến 7 triệu</button>
                    <button type="submit"  class="dropdown-item" asp-action="Index" name="price" value="4">Trên 7 triệu</button>
                </div>
             </div>
        <div class="input-group mb-3">
            <span class="input-group-text" ><i class="bi bi-search"></i></span>
                                                   
                <input type="text" class="form-control" placeholder="Nhập Tiêu đề, Giá,Diện tích hoặc Người đăng"  name="Search" value="@ViewBag.Search" >
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Tìm kiếm</button>
        </div>
      </form> 
<div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns">
<div class="dataTable-container">
<table class="table table-striped dataTable-table" >
                    <thead  role="rowgroup">
                        <tr role="row">
                            <th>Tiêu đề</th>
                            <th ><a  asp-action="Index" asp-route-sortOrder="@ViewBag.Dientich"   >Diện tích</a></th>
                            <th ><a  asp-action="Index" asp-route-sortOrder="@ViewBag.Gia" >Giá</a></th>
                            <th >Ảnh</th>
                            <th ><a asp-action="Index" asp-route-sortOrder="@ViewBag.Date" > Thời gian</a></th>
                            <th >Địa chỉ</th>
                            <th ><a asp-action="Index" asp-route-sortOrder="@ViewBag.UserName">Người đăng</a> </th>
               
                        </tr>
                    </thead>
        <tbody  role="rowgroup">
        @foreach (var item in Model) 
        {
                        <tr  role="row">
                            <td >
                              <a asp-action="Details" asp-route-id="@item.ObjNhaTro.Idtro" >@item.ObjNhaTro.TieuDe </a>
                             </td>
                            <td>@Html.DisplayFor(modelItem => item.ObjNhaTro.Dientich) m2</td>
                            <td>@item.ObjNhaTro.Gia.ToString("#,###")</td>
                            <td>
                            <a asp-action="Details" asp-route-id="@item.ObjNhaTro.Idtro">@(item.ObjNhaTro.Anh.Split(';').Count()-1). Ảnh </a>
                            </td>
                            <td>@Html.DisplayFor(modelItem => item.ObjNhaTro.Thoigiandang)</td>
                            <td>
                               @item.ObjXa.TenXa - @item.ObjKhuVuc.TenKhuVuc - @item.ObjTinh.TenTinh
                            </td>
                            <td> @Html.DisplayFor(modelItem => item.ObjNhaTro.Username)</td>
                            <td>
                                <a class="btn btn-sm btn-info" style="color:#fff" asp-action="Edit" asp-route-id="@item.ObjNhaTro.Idtro">Sửa</a>
                                 <form method="post">
                                    <button class="btn btn-sm btn-danger" style="color:#fff" style="color:#fff" asp-action="Delete" type="submit" name="id" asp-route-id="@item.ObjNhaTro.Idtro"  value="@item.ObjNhaTro.Idtro">Xoá</button>
                                </form>
                            </td>
                        </tr>
       }

           </tbody>
        </table>
        @if( Model.TotalPages!=0)
        {

                    <div class="dataTable-bottom">
                <div class="dataTable-info">Trang @Model.PageIndex / @Model.TotalPages</div>
                <ul class="pagination pagination-primary float-end dataTable-pagination">

                     @if (Model.HasPreviousPage)
            {
                <li class="page-item pager"><a asp-action="Index"
            asp-route-sortOrder="@ViewData["CurrentSort"]" 
            asp-route-pageNumber="@(Model.PageIndex - 1)"
            asp-route-currentFilter="@ViewData["CurrentFilter"]" class="page-link" >‹ trang trước</a></li>
            }
                @if (Model.HasNextPage)
            {
                    <li class="page-item pager"><a  asp-action="Index"
                    asp-route-sortOrder="@ViewData["CurrentSort"]"
                    asp-route-pageNumber="@(Model.PageIndex + 1)"
                    asp-route-currentFilter="@ViewData["CurrentFilter"]"
                    class="page-link" >trang sau ›</a></li>
            }
              </ul>

            </div>
        }
 </div>
</div>
</div>
</div>
</div>