Webnhatro_1900123/Areas/Admin/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Webnhatro_1900123.Models;


namespace Webnhatro_1900123.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    public class MemberController : Base
    {
        private readonly QuanlynhatroContext _context;

        public MemberController(QuanlynhatroContext context)
        {
            _context = context;
        }
        

        // GET: Member
        public async Task<IActionResult> Index( string sortOrder,string Search,string filter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["UserName"]= String.IsNullOrEmpty(sortOrder) ? "username_desc" : "";
            ViewData["Name"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["Date"] = sortOrder == "date" ? "date_desc" : "date";
            ViewData["search"] = Search;
            if (Search != null)
            {
                pageNumber = 1;
            }
            else
            {
                Search = filter;
            }
            ViewData["CurrentFilter"] = Search;
            //var query = (from Member in _context.Members
            //select Member).OrderBy(x => x.HoTen);
            var query = from Member in _context.Members
                         select Member;
            if (!String.IsNullOrEmpty(Search))//nếu có querystring search=
            {
                query = _context.Members.Where(s => s.HoTen.Contains(Search)
                                       || s.Username.Contains(Search)
                                       || s.Email.Contains(Search));
                //tìm kiếm bằng họ tên, username, email thành viên
            }
            switch (sortOrder)
            {
                case "name_desc":
                    query = query.OrderByDescending(s => s.HoTen);
                    break;
                case "name":
                    query = query.OrderBy(s => s.HoTen);
                    break;
                case "date":
                    query = query.OrderBy(s => s.Ngaythamgia);
                    break;
                case "date_desc":
                    query = query.OrderByDescending(s => s.Ngaythamgia);
                    break;
                case "username_desc":
                    query = query.OrderByDescending(s => s.Username);
                    break;
                default:
                    query = query.OrderBy(s => s.Username);
                    break;
            }
           
            int pageSize = 5;
            //int pageNumber = (page ?? 1);
            //return View(query.ToList());

           return View(await PaginatedList<Member>.CreateAsync(query.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: Member/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.Username == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Member/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Member/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Member member)
        {
            if (member.HoTen != null && member.Password != null && member.Username != null && member.Diachi != null && member.Email != null
                && member.Phone != null)
            {
                member.Ngaythamgia = DateTime.Now;
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else {
                TempData["Thongbao"] = "Lỗi! vui lòng kiểm tra lại dữ liệu nhập";
                return View();
            }
               
        }

        // GET: Member/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Member/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Username,Password,Phone,Email,HoTen,Diachi,Ngaythamgia")] Member member)
        {

            if (id != member.Username)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.Username))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // POST: Member/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            if (_context.Members == null)
            {
                return Problem("Entity set 'QuanlynhatroContext.Members'  is null.");
            }
            var member = await _context.Members.FindAsync(id);
            if (member != null)
            {
                _context.Members.Remove(member);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(string id)
        {
          return _context.Members.Any(e => e.Username == id);
        }
    }
}

Webnhatro_1900123/Controllers/DangtinController.cs
using Microsoft.AspNetCore.Mvc;
using Webnhatro_1900123.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace Webnhatro_1900123.Controllers
{
    public class DangtinController : sessioncheck
    {
        private QuanlynhatroContext _context;
        [Obsolete]
        private readonly IHostingEnvironment _host;

        [Obsolete]
        public DangtinController(QuanlynhatroContext context, IHostingEnvironment host)
        {
            _host = host;
            _context = context;

        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public IActionResult Index(NhaTro nhaTro, List<IFormFile> files)
        {

            nhaTro.Thoigiandang = DateTime.Now;
            var Nhatrolast = _context.NhaTros.OrderByDescending(s => s.Idtro).Take(1).ToList();//lấy Phòng trọ có số ID lớn nhất
            if (Nhatrolast.Count == 0)
                nhaTro.Idtro = "TRO1";
            else
            nhaTro.Idtro = "TRO" + Convert.ToString(Convert.ToInt32(Nhatrolast[0].Idtro.Replace("TRO", "")) + 1);//gán Id trọ = TRO+số ID lớn nhất +1
            nhaTro.Username = HttpContext.Session.GetString("user");
            ModelState.Remove("Idtro");//không cần kiểm tra key Idtro có hợp lệ hay k
                                       //thêm ảnh vào thư mục upload
            if (files != null && ModelState.IsValid)
            {
                int i = 1;
                foreach (var file in files)
                {
                    string filename = file.FileName;
                    string fileextension = Path.GetExtension(filename);
                    filename = nhaTro.Idtro + "_Anh" + i.ToString() + fileextension;
                    var pathsave = Path.Combine(_host.WebRootPath + @"\Upload\NhaTro", filename);//đường đãn lưu file  _host.WebRootPath:chỉ wwwroot 
                    if (System.IO.File.Exists(pathsave))//nếu đã tồn tại-->xoá-->lưu
                    {
                        System.IO.File.SetAttributes(pathsave, FileAttributes.Normal);
                        System.IO.File.Delete(pathsave);
                        using var stream = new FileStream(pathsave, FileMode.Create);
                        file.CopyTo(stream);
                    }
                    else//chưa có thực hiện lưu vào thư mục
                    {
                        using var stream = new FileStream(pathsave, FileMode.Create);
                        file.CopyTo(stream);

                    }
                    nhaTro.Anh += $"{filename};";
                    i++;
                }
                _context.Add(nhaTro);
                _context.SaveChanges();//lưu database
                TempData["Messenger"] = "Tin của bạn đã được đăng thành công";
                return RedirectToAction("Index", "House");
            }
            else
            {
                TempData["Thongbao"] = "Lỗi! vui lòng kiểm tra lại dữ liệu nhập";
                return View();
            }

        }
    }
}

Webnhatro_1900123/Controllers/HouseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Webnhatro_1900123.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace Webnhatro_1900123.Controllers
{
    public class HouseController : Controller
    {
        private readonly QuanlynhatroContext _context;
        [Obsolete]
        private readonly IHostingEnvironment _host;
        [Obsolete]
        public HouseController(QuanlynhatroContext context, IHostingEnvironment host)
        {
            _host = host;
            _context = context;
            
        }
        public async Task<IActionResult> Index(string key, int? pageNumber, string? price, string? S, string? sortOrder, string? T, string? Kv, string? x)
        {

            ViewData["T"] = T;
            ViewData["Kv"] = Kv;
            ViewData["x"] = x;
            ViewData["S"] = S;
            ViewData["price"] = price;
            ViewData["sortOrder"] = sortOrder;
            //if (string.IsNullOrEmpty(Search)) ;
            IQueryable<Nhatrofull> query = (
              from NhaTro in _context.NhaTros
              join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
              join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
              join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
              select new Nhatrofull
              {
                  ObjNhaTro = NhaTro,
                  ObjXa = Xa,
                  ObjKhuVuc = KhuVuc,
                  ObjTinh = Tinh
              });
            if (!string.IsNullOrEmpty(T))
            {
                query = query.Where(s => s.ObjTinh.Idtinh == T);
            }
            if (!string.IsNullOrEmpty(Kv))
            {
                query = query.Where(s => s.ObjKhuVuc.IdkhuVuc == Kv);
            }     
            if (!string.IsNullOrEmpty(x))
            {
                query = query.Where(s => s.ObjXa.Idxa == x);
            }
            if (!string.IsNullOrEmpty(sortOrder))
            {
                switch (sortOrder)
                {
                    case "moinhat":
                        query = query.OrderByDescending(s => s.ObjNhaTro.Thoigiandang);
                        break;
                    case "price":
                        query = query.OrderBy(s => s.ObjNhaTro.Gia);
                        break;
                    case "price_desc":
                        query = query.OrderByDescending(s => s.ObjNhaTro.Gia);
                        break;
                }
            }
            if (!string.IsNullOrEmpty(price))
            {
                switch (price)
                {
                    case "1":
                        query = query.Where(s => s.ObjNhaTro.Gia < 1000000);
                        break;
                    case "2":
                        query = query.Where(s => s.ObjNhaTro.Gia >= 1000000 &&s.ObjNhaTro.Gia<3000000);
                        break;
                    case "3":
                        query = query.Where(s => s.ObjNhaTro.Gia >= 3000000 && s.ObjNhaTro.Gia<5000000);
                        break;
                    case "4":
                        query = query.Where(s => s.ObjNhaTro.Gia >= 5000000 && s.ObjNhaTro.Gia<7000000);
                        break;
                    case "5":
                        query = query.Where(s => s.ObjNhaTro.Gia > 7000000);
                        break;
                }
            }
            if (!string.IsNullOrEmpty(S))
            {
                switch (S)
                {
                    case "1":
                        query = query.Where(s => s.ObjNhaTro.Dientich < 20);
                        break;
                    case "2":
                        query = query.Where(s => s.ObjNhaTro.Dientich >= 20&&s.ObjNhaTro.Dientich<40);
                        break;
                    case "3":
                        query = query.Where(s => s.ObjNhaTro.Dientich >=40 &&s.ObjNhaTro.Dientich<60);
                        break;
                    case "4":
                        query = query.Where(s => s.ObjNhaTro.Dientich > 60);
                        break;
                }
               
            }
            if (!string.IsNullOrEmpty(key))
            {
                query = query.Where(s => s.ObjNhaTro.TieuDe.Contains(key) || s.ObjNhaTro.Thongtin.Contains(key)
                || s.ObjKhuVuc.TenKhuVuc.Contains(key) || s.ObjXa.TenXa.Contains(key));
            }
                int pageSize = 10;
            return View(await PaginatedList<Nhatrofull>.CreateAsync(query.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var item = from NhaTro in _context.NhaTros
                       where NhaTro.Idtro == id
                       join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
                       join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
                       join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
                       join Member in _context.Members on NhaTro.Username equals Member.Username
                       select new Nhatrofull
                       {
                           ObjNhaTro = NhaTro,
                           ObjXa = Xa,
                           ObjKhuVuc = KhuVuc,
                           ObjTinh = Tinh,
                           objMember = Member
                       };
            var query = (from NhaTro in _context.NhaTros
                         where NhaTro.Idtro != id
                         join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
                         join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
                         join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
                         select new Nhatrofull
                         {
                             ObjNhaTro = NhaTro,
                             ObjXa = Xa,
                             ObjKhuVuc = KhuVuc,
                             ObjTinh = Tinh
                         }).Take(5).ToList();
            ViewData["Samelocation"] = query;

            if (item != null)
            {
                return View(item.First());
            }
            return NotFound();

        }



    }
}

Webnhatro_1900123/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Webnhatro_1900123.Models;

namespace Webnhatro_1900123.Controllers
{
    public class NewsController : Controller
    {
        private readonly QuanlynhatroContext _context;
        public NewsController(QuanlynhatroContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var query = from TinTuc in _context.TinTucs
                        orderby TinTuc.NgayDang descending
                        select TinTuc;
           int pageSize = 10;
            return View(await PaginatedList<TinTuc>.CreateAsync(query.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        public async Task<IActionResult> Chitiet(string id)
        {
          var objtintuc= await _context.TinTucs.FindAsync(id);
            var query= _context.TinTucs.Where(s => s.Idnews != id).Take(5).ToList();

            ViewBag.List = query;
            if (objtintuc == null)
            {
                return NotFound();
            }
            return View(objtintuc);
        }
       
           
    }
}

Webnhatro_1900123/Views/Shared/_Layout -nosearch.cshtml
@{
   string name= Context.Session.GetString("Fullname");
       if (ViewData["Title"] == null)
    {
         ViewData["Title"] = "Trang chủ-Webthuetro";
    }
}
<html lang="vi"><head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0">
       <title>@ViewData["Title"]</title>
    <meta name="robots" content="index,follow">
    <meta name="keywords" content="thue phong tro, cho thuê phòng trọ, tim phong tro, thue nha tro, phòng trọ, nhà trọ">
     <meta name="placename" content="Việt Nam">
    <link rel="icon" href="User/images/favicon.ico">
  <link rel="stylesheet" href="~/Template/dist/assets/css/bootstrap.css">
    <link rel="stylesheet" href="~/Template/dist/assets/vendors/iconly/bold.css">
    <link rel="stylesheet" href="~/Template/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/Template/dist/assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/app.css">
</head>
<body class="bg-light">    
  <nav class="navbar navbar-fixed bg d-flex w-100 opacity-100 shadow">
    <div class="px-1">
      <a asp-action="Index" asp-controller="Home">
        <img class="logo" src="/logo.png" alt="icon">
      </a>
    </div>
    <div class="end-0 position-absolute">
      <button class="navbar-toggler me-1 text-dark collapsed" type="button" onclick="sidebar()">
        <i class="bi bi-justify fs-3"></i>
      </button>
    </div>    
  </nav>
  <div id="sidebar" class="pt-2">
    <div class="sidebar-wrapper active bg-light">
        <div class="sidebar-header py-0">
            <div class="d-flex justify-content-between">
                @if(!string.IsNullOrEmpty(name))
                {
                <div>
                    <span class="fs-5 font-bold text-dark">Xin chào,@name</span>
                </div>
                }
                 else
                {
                <div class="fs-6 mt-4 mb-0">
                    <a asp-action="Dangnhap" asp-controller="Home"> Đăng nhập</a>/
                    <a asp-action="Dangky" asp-controller="Home"> Đăng ký</a>
                </div>
                }
                <div class="toggler">
                    <a onclick="sidebar()" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                </div>
            </div>
        </div>
        <div class="sidebar-menu h-auto">
            <ul class="menu" onclick="activesidebar(event)">
                <li class="sidebar-title">Menu</li>
                <li class="sidebar-item">
                    <a asp-action="Index" asp-controller="Home" class="sidebar-link">
                        <i class="bi bi-grid-fill"></i>
                        <span>Trang chủ</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a asp-action="Index" asp-controller="House" class="sidebar-link">
                        <i class="bi bi-house-fill"></i>
                        <span>Nhà trọ</span>
                    </a>
                </li>
                <li class="sidebar-item  ">
                  <a asp-action="Index" asp-controller="News" class="sidebar-link">
                      <i class="bi bi-newspaper"></i>
                      <span>Tin tức</span>
                  </a>
              </li>
              <li class="sidebar-item  ">
                <a  asp-action="Index" asp-controller="Dangtin" class="sidebar-link">
                    <i class="bi bi-pencil-fill"></i>
                    <span>Đăng tin</span>
                </a>
            </li>
            </ul>
        </div>
        <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
    @if (!string.IsNullOrEmpty(name))
            {
                <div class="position-absolute bottom-0 w-100 ">
                    <a asp-action="logout" asp-controller="Home" class="btn btn-primary font-bold w-100">Đăng xuất 
                        <svg class="fa-sign-out-alt icon" data-icon="sign-out-alt" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg="">
                        <path fill="currentColor" d="M497 273L329 441c-15 15-41 4.5-41-17v-96H152c-13.3 0-24-10.7-24-24v-96c0-13.3 10.7-24 24-24h136V88c0-21.4 25.9-32 41-17l168 168c9.3 9.4 9.3 24.6 0 34zM192 436v-40c0-6.6-5.4-12-12-12H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h84c6.6 0 12-5.4 12-12V76c0-6.6-5.4-12-12-12H96c-53 0-96 43-96 96v192c0 53 43 96 96 96h84c6.6 0 12-5.4 12-12z"></path>
                        </svg>
                    </a>
                 </div>
      }
    <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; height: 864px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 452px;"></div></div></div>
  </div>


    @RenderBody();

<footer>
  <div class="container">
        <div class="col  text-center">
          <div class="row">
            <div class="border-top pt-3">
              <div class="company">
                  <p>
                    <strong>Cho thuê phòng trọ nhanh chóng và hiệu quả</strong>
                  </p>
                  <p>CSKH: 0363.598.860</p>
                  <p>Email: webthuetro@gmail.com</p>
                  <p>Copyright © 2022 webthuetro.com</p>
                  <p>Địa chỉ: 74 - Phố Hữu Nghị - Phường Xuân Khanh - TX.Sơn Tây - Hà Nội</p>
                  <span class="fs-6">Đồ án học phần 2 - ASP.NET MVC</span>
                </div>
            </div>
          </div>

        </div>
      </div>
</footer>
</body>
<script src="~/Template/dist/assets/js/main.js"> </script>
<script src="~/Template/dist/assets/js/bootstrap.bundle.min.js"> </script>
<script src="~/js/axios.min.js"></script>
<script src="~/js/Diadiem.js"></script>
<script>
      function sidebar(){
    document.getElementById('sidebar').classList.toggle('active')
  }
</script>
@section Scripts 
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</html>

Webnhatro_1900123/Views/Shared/_Layoutadmin.cshtml
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @if (ViewData["Title"] == null)
    {
        <title>Trang quản trị</title>
    }
    else
    {
          <title>@ViewData["Title"]</title>
    }
  

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Template/dist/assets/css/bootstrap.css">

    <link rel="stylesheet" href="~/Template/dist/assets/vendors/iconly/bold.css">

    <link rel="stylesheet" href="~/Template/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/Template/dist/assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Template/dist/assets/css/app.css">
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active ps ps--active-y">
                <div class="sidebar-header">
                    <div class="d-flex justify-content-between">
                        <div class="logo">
                            <a asp-action="Index" asp-controller="Home"><img src="~/Template/dist/assets/images/logo/logo.png" alt="Logo" srcset=""></a>
                        </div>
                        <div class="toggler">
                            <a href="#" class="sidebar-hide d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>

                <div class="sidebar-menu">
                    <ul class="menu" >
                  <li class="sidebar-title" ><a class="sidebar-link"  asp-area="Admin" asp-controller="Home" asp-action="Index">Quản trị</a></li>
				 <li class="sidebar-title" ><a class="sidebar-link"  asp-area="Admin" asp-controller="Member" asp-action="Index">Quản lý member</a></li>
				 <li class="sidebar-title" ><a class="sidebar-link"  asp-area="Admin" asp-controller="NhaTro" asp-action="Index">Quản lý nhà trọ</a></li>
				 <li class="sidebar-title" ><a class="sidebar-link"  asp-area="Admin" asp-controller="TinTuc" asp-action="Index">Quản lý Tin Tức</a></li>
                 <li class="sidebar-title" ><a class="sidebar-link"  asp-area="" asp-controller="Home" asp-action="Index">Trang người dùng</a></li>
                  <li class="sidebar-title" ><a class="sidebar-link"  asp-area="Admin" asp-controller="Login" asp-action="Logout">Đăng xuất</a></li>
                    </ul>
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; height: 764px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 353px;"></div></div></div>
        </div>
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block end-0 pe-1">
                    <i class="bi bi-justify fs-3" style="display:block"></i>
                </a>
            </header>
            <div class="page-content">
                <section class="row">
                    @RenderBody()
                    
                </section>
            </div>



            <footer>
                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                        <p>2022 © đồ án học phần 2 - ASP-MVC 6.0</p>
                    </div>
                    <div class="float-end">
                        <p>Web phòng trọ <span class="text-danger"><i class="bi bi-heart"></i></span> by <a href="https://www.facebook.com/lanh.lv.39">Lương Văn Lanh</a></p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/Template/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/Template/dist/assets/js/bootstrap.bundle.min.js"></script>
    <script src="~/Template/dist/assets/js/pages/dashboard.js"></script>
    <script src="~/Template/dist/assets/js/main.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
    <script>
		function openmenu() {
document.getElementById('wrapper').classList.toggle('toggled');}
		</script>
    
	

</body>
</html>