Webnhatro_1900123/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Webnhatro_1900123.Models;

namespace Webnhatro_1900123.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Base
    {
        public IActionResult Index()
        {
            ViewData["Hoten"] = HttpContext.Session.GetString("Hoten");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Webnhatro_1900123/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Webnhatro_1900123.Models;

namespace Webnhatro_1900123.Controllers
{
    
    public class HomeController : Controller
    {
        private QuanlynhatroContext _context;
        public HomeController(QuanlynhatroContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? pageNumber)
        {
            IQueryable<Nhatrofull> query = (
              from NhaTro in _context.NhaTros
              join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
              join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
              join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
              select new Nhatrofull
              {
                  ObjNhaTro = NhaTro,
                  ObjXa = Xa,
                  ObjKhuVuc = KhuVuc,
                  ObjTinh = Tinh
              });
            IQueryable<TinTuc> top5 = (from TinTuc in _context.TinTucs orderby TinTuc.NgayDang descending
                                      select TinTuc).Take(5);
            ViewData["News"]=top5.ToList();
            int pageSize = 10;
            return View(await PaginatedList<Nhatrofull>.CreateAsync(query.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            TempData["Messenger"] = "Bạn đã đăng xuất";
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]

        public IActionResult Dangnhap(string username, string password)
        {

            var query = from Member in _context.Members
                        select Member;
            foreach (var member in query)
            {
                if (username == member.Username && password == member.Password)
                {
                    HttpContext.Session.SetString("user", member.Username);
                    HttpContext.Session.SetString("Fullname", member.HoTen);
                    TempData["Messenger"] = "Đăng nhập thành công," + member.HoTen;
                    return RedirectToAction("Index", "Home");
                }
            }
            TempData["thongbao"] = "Đăng nhập thất bại,kiểm tra lại thông tin";
            return View(TempData["thongbao"]);
        }
        public IActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Dangky(Member member)
        {
            member.Ngaythamgia = DateTime.Now;
            if (validuser(member.Username))
            {
                TempData["thongbao"] = $"tên đăng nhập {member.Username} đã tồn tại vui lòng chọn tên đăng nhập khác";
                return View();
            }
            else if (ModelState.IsValid)
            {
                _context.Members.Add(member);
                _context.SaveChanges();
                HttpContext.Session.SetString("user", member.Username);
                HttpContext.Session.SetString("Fullname", member.HoTen);
                TempData["Messenger"] = "Đăng nhập thành công," + member.HoTen;
                return RedirectToAction("Index", "Home");

            }
            return View();
        }
        bool validuser(string username)
        {
            List<string> listusername = _context.Members.Select(s => s.Username).ToList();
            foreach (var item in listusername)
            {
                if (item == username)
                {
                   return true;
                }
            }
            return false;
        }
    }
}

Webnhatro_1900123/Controllers/HouseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Webnhatro_1900123.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace Webnhatro_1900123.Controllers
{
    public class HouseController : Controller
    {
        private readonly QuanlynhatroContext _context;
        [Obsolete]
        private readonly IHostingEnvironment _host;
        [Obsolete]
        public HouseController(QuanlynhatroContext context, IHostingEnvironment host)
        {
            _host = host;
            _context = context;
            
        }
        public async Task<IActionResult> Index(string key, int? pageNumber, string? price, string? S, string? sortOrder, string? T, string? Kv, string? x)
        {

            ViewData["T"] = T;
            ViewData["Kv"] = Kv;
            ViewData["x"] = x;
            ViewData["S"] = S;
            ViewData["price"] = price;
            ViewData["sortOrder"] = sortOrder;
            //if (string.IsNullOrEmpty(Search)) ;
            IQueryable<Nhatrofull> query = (
              from NhaTro in _context.NhaTros
              join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
              join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
              join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
              select new Nhatrofull
              {
                  ObjNhaTro = NhaTro,
                  ObjXa = Xa,
                  ObjKhuVuc = KhuVuc,
                  ObjTinh = Tinh
              });
            if (!string.IsNullOrEmpty(T))
            {
                query = query.Where(s => s.ObjTinh.Idtinh == T);
            }
            if (!string.IsNullOrEmpty(Kv))
            {
                query = query.Where(s => s.ObjKhuVuc.IdkhuVuc == Kv);
            }     
            if (!string.IsNullOrEmpty(x))
            {
                query = query.Where(s => s.ObjXa.Idxa == x);
            }
            if (!string.IsNullOrEmpty(sortOrder))
            {
                switch (sortOrder)
                {
                    case "moinhat":
                        query = query.OrderByDescending(s => s.ObjNhaTro.Thoigiandang);
                        break;
                    case "price":
                        query = query.OrderBy(s => s.ObjNhaTro.Gia);
                        break;
                    case "price_desc":
                        query = query.OrderByDescending(s => s.ObjNhaTro.Gia);
                        break;
                }
            }
            if (!string.IsNullOrEmpty(price))
            {
                switch (price)
                {
                    case "1":
                        query = query.Where(s => s.ObjNhaTro.Gia < 1000000);
                        break;
                    case "2":
                        query = query.Where(s => s.ObjNhaTro.Gia >= 1000000 &&s.ObjNhaTro.Gia<3000000);
                        break;
                    case "3":
                        query = query.Where(s => s.ObjNhaTro.Gia >= 3000000 && s.ObjNhaTro.Gia<5000000);
                        break;
                    case "4":
                        query = query.Where(s => s.ObjNhaTro.Gia >= 5000000 && s.ObjNhaTro.Gia<7000000);
                        break;
                    case "5":
                        query = query.Where(s => s.ObjNhaTro.Gia > 7000000);
                        break;
                }
            }
            if (!string.IsNullOrEmpty(S))
            {
                switch (S)
                {
                    case "1":
                        query = query.Where(s => s.ObjNhaTro.Dientich < 20);
                        break;
                    case "2":
                        query = query.Where(s => s.ObjNhaTro.Dientich >= 20&&s.ObjNhaTro.Dientich<40);
                        break;
                    case "3":
                        query = query.Where(s => s.ObjNhaTro.Dientich >=40 &&s.ObjNhaTro.Dientich<60);
                        break;
                    case "4":
                        query = query.Where(s => s.ObjNhaTro.Dientich > 60);
                        break;
                }
               
            }
            if (!string.IsNullOrEmpty(key))
            {
                query = query.Where(s => s.ObjNhaTro.TieuDe.Contains(key) || s.ObjNhaTro.Thongtin.Contains(key)
                || s.ObjKhuVuc.TenKhuVuc.Contains(key) || s.ObjXa.TenXa.Contains(key));
            }
                int pageSize = 10;
            return View(await PaginatedList<Nhatrofull>.CreateAsync(query.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var item = from NhaTro in _context.NhaTros
                       where NhaTro.Idtro == id
                       join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
                       join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
                       join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
                       join Member in _context.Members on NhaTro.Username equals Member.Username
                       select new Nhatrofull
                       {
                           ObjNhaTro = NhaTro,
                           ObjXa = Xa,
                           ObjKhuVuc = KhuVuc,
                           ObjTinh = Tinh,
                           objMember = Member
                       };
            var query = (from NhaTro in _context.NhaTros
                         where NhaTro.Idtro != id
                         join Xa in _context.Xas on NhaTro.Idxa equals Xa.Idxa
                         join KhuVuc in _context.KhuVucs on Xa.IdkhuVuc equals KhuVuc.IdkhuVuc
                         join Tinh in _context.Tinhs on KhuVuc.Idtinh equals Tinh.Idtinh
                         select new Nhatrofull
                         {
                             ObjNhaTro = NhaTro,
                             ObjXa = Xa,
                             ObjKhuVuc = KhuVuc,
                             ObjTinh = Tinh
                         }).Take(5).ToList();
            ViewData["Samelocation"] = query;

            if (item != null)
            {
                return View(item.First());
            }
            return NotFound();

        }



    }
}

Webnhatro_1900123/Views/Home/Dangky.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Đăng ký";
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đăng ký - Webthuetro.com</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Template/dist/assets/css/bootstrap.css">
    <link rel="stylesheet" href="~/Template/dist/assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Template/dist/assets/css/app.css">
    <link rel="stylesheet" href="~/Template/dist/assets/css/pages/auth.css">
</head>

<body class="bg-light">
@using (Html.BeginForm("Dangky","Home",FormMethod.Post))
{
    <div class="card mx-4 my-4 position-relative">
        <div class="mb-3">
              <a asp-action="Index" asp-controller="Home"><img src="~/logo.png" style="width:200px" alt="Logo"></a>
        </div>
            <div class="col-12">
                <div class="card py-2">
                    <div class="card-header">
                        <h4 class="card-title">Đăng Ký thành viên</h4>
                    </div>
                    @if (TempData["thongbao"]!=null)
                    {
                       <div class="alert alert-light-danger color-danger"><i class="bi bi-exclamation-circle"></i>@TempData["thongbao"]</div>
                    }
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-xl-6">
                                <label>Tên người dùng</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="text" class="form-control" placeholder="Nhập username" name="Username">
                                    <div class="form-control-icon">
                                        <i class="bi bi-person"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-6">
                                <label>Mật khẩu</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="password" class="form-control" placeholder="********" name="Password">
                                    <div class="form-control-icon">
                                        <i class="bi bi-shield-lock"></i>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-12 col-xl-6">
                                <label>Số điện thoại</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="tel" class="form-control" placeholder="098..." name="Phone" pattern="[0-9]{10}" title="bao gồm 10 chữ số">
                                    <div class="form-control-icon">
                                        <i class="bi bi-phone"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-6">
                                <label>Email</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="email" class="form-control" placeholder="abc@example.com" name="Email">
                                    <div class="form-control-icon">
                                        <i class="bi bi-mailbox"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-6">
                                <label>Họ và tên</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="text" class="form-control" placeholder="Nguyễn Văn A...." name="HoTen">
                                    <div class="form-control-icon">
                                        <i class="bi bi-card-list"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-6">
                                <label>Địa chỉ</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="text" class="form-control" placeholder="Số nhà-Phường...." name="Diachi">
                                    <div class="form-control-icon">
                                        <i class="bi bi-geo-alt"></i>
                                    </div>
                                </div>
                            </div>  
                        </div>
                        <div class="d-flex justify-content-center">
                            <button class="btn btn-primary px-4" type="submit" >Đăng ký</button>
                        </div>
                        <div class="mt-4 d-flex justify-content-center">
                            Đã có tài khoản? <a asp-action="Dangnhap" asp-controller="Home">Đăng Nhập</a>
                        </div>
                       
                    </div>
                </div>
            </div>
    </div>
}
</body>

</html>

Webnhatro_1900123/Views/Home/Dangnhap.cshtml
@{
    Layout = null;
    ViewData["Title"]="Đăng nhập";
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đăng Nhập</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Template/dist/assets/css/bootstrap.css">
    <link rel="stylesheet" href="~/Template/dist/assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Template/dist/assets/css/app.css">
    <link rel="stylesheet" href="~/Template/dist/assets/css/pages/auth.css">
</head>

<body class="bg-light">
@using (Html.BeginForm("Dangnhap","Home",FormMethod.Post))
{
    <div class="row justify-content-center">
        <div class="col-md-6 mx-4 my-4 position-relative">
            <div class="mb-3">
                <a asp-action="Index" asp-controller="Home"><img src="~/logo.png" style="width:200px" alt="Logo"></a>
            </div>
         <div class="col-12">
                <div class="card py-2">
                    <div class="card-header text-center">
                        <h4 class="card-title">Đăng Nhập</h4>
                    </div>
                    @if (TempData["thongbao"] != null)
                    {
                        <div class="alert alert-light-danger color-danger"><i class="bi bi-exclamation-circle"></i>@TempData["thongbao"]</div>
                    }
                    <div class="card-body">
                        <form method="post">
                        <div class="row">
                            <div class="col-12">
                                <label>Tên người dùng</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="text" name="Username" class="form-control" placeholder="Nhập username">
                                    <div class="form-control-icon">
                                        <i class="bi bi-person"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <label>Mật khẩu</label>
                                <div class="form-group position-relative has-icon-left">
                                    <input type="password" name="Password" class="form-control" placeholder="********">
                                    <div class="form-control-icon">
                                        <i class="bi bi-shield-lock"></i>
                                    </div>
                                </div>
                            </div>
                        <div class="d-flex justify-content-center">
                            <button class="btn btn-primary px-4" type="submit">Đăng Nhập</button>
                        </div>
                        <div class="mt-4 d-flex justify-content-center">
                            Chưa có tài khoản? 
                            <a asp-action="Dangky" asp-controller="Home"> Đăng ký</a>
                         </div>
                        <div class="mt-4 d-flex justify-content-center">
                           Quên mật khẩu? Vui lòng liên hệ với quản trị viên
                        </div>
                       
                      </div>
                    </form>
                </div>
            </div>
         </div>
        </div>
    </div>
 }
</body>

</html>

Webnhatro_1900123/Views/Home/Index.cshtml
@model PaginatedList<Webnhatro_1900123.Models.Nhatrofull>
@{
    ViewData["Title"] = "Web Nhà trọ by Lvlanh";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="webpage">
  <main id="main">
       @if(TempData["Messenger"] != null)
        {
            <div id="toast" class="alert alert-success alert-dismissible show fade bottom-3 end-0 position-fixed"><i class="bi bi-check-circle"></i> @TempData["Messenger"]</div>
        }
    <div class="section section-top-location bg-white">
      <div class="section-content">
        <div class="top-location city d-flex">
         <a class="location-item city-1" asp-action="Index" asp-controller="House" asp-route-T="79" title="Cho thuê nhà Hồ Chí Minh">
            <i></i>
            <span>Cho thuê nhà <span class="city-name">Hồ Chí Minh</span>
            </span>
          </a>
          <a class="location-item city-2" asp-action="Index" asp-controller="House" asp-route-T="01" title="Cho thuê nhà Hà Nội">
            <i></i>
            <span>Cho thuê nhà <span class="city-name">Hà Nội</span>
            </span>
          </a>
          <a class="location-item city-4" asp-action="Index" asp-controller="House" asp-route-T="48" title="Cho thuê nhà Đà Nẵng">
            <i></i>
            <span>Cho thuê nhà <span class="city-name">Đà Nẵng</span>
            </span>
          </a>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="section-header">
        <span class="section-title">Danh sách nhà trọ đã đăng</span>
      </div>
      <div class="section-content">
        <div class="home-listing ">
          <ul class="home-sort clearfix pt-2" id="sort">  
              <span>Sắp xếp: </span>
            <li>
              <a  class="active">Mặc định</a>
            </li>
           <li>
              <a class="" asp-controller="House" asp-action="Index" asp-route-sortOrder="moinhat">Mới nhất</a>
            </li>
            <li>
              <a class="" asp-controller="House" asp-action="Index" asp-route-sortOrder="price">Giá thấp nhất</a>
            </li>
             <li>
              <a class="" asp-controller="House" asp-action="Index" asp-route-sortOrder="price_desc">Giá cao nhất</a>
            </li>
          </ul>
@foreach(var item in Model)
{
        <article class="home-item clearfix free ">
            <figure class="home-thumb">
                <a asp-controller="House" asp-action="Details" asp-route-id="@item.ObjNhaTro.Idtro" >
                    <img alt="@item.ObjNhaTro.TieuDe" class="lazy_done" src="~/Upload/NhaTro/@item.ObjNhaTro.Anh.Split(';')[0]" data-loaded="true">
                </a>
              <span class="home-save js-btn-save" data-post-id="200136712">
                <i class="icon heart white size-20 margin-right-0"></i>
              </span>
              <span class="images-count">@(item.ObjNhaTro.Anh.Split(';').Length-1) ảnh</span>
            </figure>
            <div class="home-meta">
              <h4 class="home-title">
                <a title="@item.ObjNhaTro.TieuDe" style="color: #055699;" asp-controller="House" asp-action="Details" asp-route-id="@item.ObjNhaTro.Idtro">
                  @item.ObjNhaTro.TieuDe </a>
              </h4>
              <div class="meta-row clearfix">
                <span class="home-price">@item.ObjNhaTro.Gia.ToString("#,###") <i>VNĐ</i>
                </span>
              </div>
              <div class="meta-row clearfix">
                <span class="home-acreage">@item.ObjNhaTro.Dientich m<sup>2</sup>
                </span>
              </div>
              <span class="home-location">
                 @item.ObjXa.TenXa-@item.ObjKhuVuc.TenKhuVuc-@item.ObjTinh.TenTinh
              </span>
              <span class="home-publish">@item.ObjNhaTro.Thoigiandang.ToString("dd/MM/yyyy")</span>
            </div>
          </article>
}
        </div>
   <div style="direction: rtl">Trang @Model.PageIndex / @Model.TotalPages</div>
        <nav aria-label="Page navigation">
                    <ul class="pagination pagination-danger p-0 m-0">
                        @if (Model.HasPreviousPage)
                        {
                             <li class="page-item"><a class="page-link" 
                                        asp-action="Index"
                                        asp-route-sortOrder="@ViewBag.sortOrder" 
                                        asp-route-pageNumber="@(Model.PageIndex - 1)"
                                        asp-route-currentFilter="@ViewData["CurrentFilter"]">
                                 <span aria-hidden="true"><i class="bi bi-chevron-left"></i></span></a>
                             </li>
                        }
                         <li class="page-item active"><a class="page-link" >@Model.PageIndex</a></li>
                        @if (Model.HasNextPage)
                        {
                             <li class="page-item"><a class="page-link" asp-action="Index"
                                asp-route-sortOrder="@ViewBag.sortOrder" 
                                asp-route-pageNumber="@(Model.PageIndex - 1)"
                                asp-route-currentFilter="@ViewData["CurrentFilter"]">
                                <span aria-hidden="true"><i class="bi bi-chevron-right"></i></span>
                              </a></li>
                        }
                    </ul>
        </nav>
      </div>
    </div>
  <div class="section">
      <div class="section-header">
            <span class="section-title">Tin tức mới</span>
      </div>
      <section class="section bg-white py-0">
        <div class="blog-listing">
          <div class="inner">
@foreach(var news in ViewData["News"] as List<TinTuc>)
{
            <article class="article-item clearfix py-0">
                <a asp-action="Chitiet" asp-controller="News" asp-route-id="@news.Idnews" title="@news.Title">
                <figure>
                    <img src="~/Upload/News/@news.Anh.Split(';')[0]" alt="@news.Title" title="@news.Title">
                </figure>
                <div class="article-meta">
                    <h3 class="article-title">@news.Title</h3>
                    <div class="article-publish">
                    <i class="icon clock size-14 margin-right-2"></i> @news.NgayDang.ToString("dd/MM/yyyy")
                    </div>
                </div>
                </a>
            </article>
}
          </div>
        </div>
      </section>
</div>
  </main>
</div>
<script src="~/js/axios.min.js"></script>
<script src="~/js/Diadiem.js"></script>
<script>
setTimeout(() => {
    const toast = document.getElementById('toast');
    toast.style.display = 'none';
}, 3000);
</script>